version: '3.9'

services:
  airflow:
    image: apache/airflow:latest
    volumes:
      - ./shared_modules:/opt/airflow/shared_modules
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: 'thisisasecretkey'
    command: standalone

  db:
    image: postgres:16-alpine
    container_name: company_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
