version: '3.9'

services:
  airflow:
    build: ./airflow
    volumes:
      - ./shared_modules:/opt/airflow/shared_modules
      - ./airflow/dags:/opt/airflow/dags
      - ./company_db_setup:/opt/airflow/company_db_setup
      - ./config.yaml:/opt/airflow/config.yaml
      - ./airflow/scripts:/opt/airflow/scripts
      - ./config.yaml:/opt/airflow/config.yaml
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: 'thisisasecretkey'
      AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: 'admin'
      AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: 'admin'
      AIRFLOW__WEBSERVER__DEFAULT_USER_EMAIL: 'admin@example.com'
      AIRFLOW__WEBSERVER__DEFAULT_USER_FIRST_NAME: 'Air'
      AIRFLOW__WEBSERVER__DEFAULT_USER_LAST_NAME: 'Flow'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    command: standalone

  db:
    image: postgres:16-alpine
    container_name: company_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
